name: tokolint
on: push
env:
  GOPRIVATE: "github.com/tokopedia/*"
  GOPATH: ${{ github.workspace }}/go
  GO111MODULE: on
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.MY_GITHUB_ACCESS_TOKEN  }}
          USER_NAME: ${{ secrets.MY_GITHUB_USER_NAME }}
        run: git config --global url."https://${USER_NAME}:${TOKEN}@github.com".insteadOf "https://github.com"
      - uses: actions/checkout@v2
      - name: Checkout tokolint action
        uses: actions/checkout@v2
        with:
          repository: tokopedia/tokolint
          ref: main
          token: ${{ secrets.MY_GITHUB_ACCESS_TOKEN  }}
          path: .github/actions/tokolint
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Run tokolint action
        uses: ./.github/actions/tokolint
        with:
          # github token
          github-token: ${{ secrets.MY_GITHUB_ACCESS_TOKEN  }}

          # version is the tokolint release version
          version: latest

          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          args: --verbose

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: false